### ISSUE TITLE
Why does every update necessitate running VSCode as administrator?

### ISSUE THREAD

**Issue by Arrow7000** [robertohuertasm/vscode-icons#234]
I have to say it's annoying as hell to get continuous updates and not being able to enable them without having to quit everything I'm doing, shut down the VSCode (including the usual 3 integrated terminals I'm running) and restarting, only for it to tell me that I need to start it again in admin mode, which I then do, and then I again need to restart it. 

Why does this extension require me to run it in administrator mode, when no other extension requires me to do so?

**Comment by jens1o** [comment]
We need the administrative right, to inject code in vscode to be able to display the icons, due the api it is currently used is not supported in the extension, yet.

**Comment by robertohuertasm** [comment]
I take for granted that you haven't even bothered to read the the readme but it will be enough to say that this extension, as Microsoft hasn't offered a proper extension API for icons, modifies some of the core files of VSCode and that's why it needs your permission to make it.

If you're so annoyed by this I'd suggest you to start always in admin mode. It's a simple checkbox that you have to check by right clicking over your vscode icon and selecting Properties > Advanced > Run as Administrator.
