### ISSUE TITLE
when dir name is script/scripts, the icon is blank~

### ISSUE THREAD

**Issue by jaylinwang** [robertohuertasm/vscode-icons#262]
when dir name is script/scripts, the icon is blank~

this is screen snapshot:

![a87f55b1-60d6-4fb3-92ef-9177cd007343](https://cloud.githubusercontent.com/assets/4530355/18224077/65846de8-71fc-11e6-9ac3-dbae65a6f029.png)

- I'm using Visual Studio Code Version [1.4.0]
- I'm using the extension version [1.8.9]

**Comment by jens1o** [comment]
I cannot reproduce that.

**Comment by jaylinwang** [comment]
i'm use osx

**Comment by robertohuertasm** [comment]
@jaylinwang does it only happen with this special folder? The OS should not have any effect in this case.
If the icon is not being loaded is that you don't have it on your machine. In order to assure you have all what it's needed I would suggest you to completely reinstall the extension:

1. Icons disable
2. Uninstall the extension.
3. Reinstall the extension.
4. Icons Enable if the autorun doesn't start.
5. Check if you have your icon back and let us know.

It has happen sometimes to other users and these steps usually help.

**Comment by jaylinwang** [comment]
when i reinstall the extension, i's ok~

thanks 😄
