### ISSUE TITLE
Improvements to avoid asking admin permissions after updating

### ISSUE THREAD

**Issue by be5invis** [robertohuertasm/vscode-icons#267]
Separate the file/folder identification part (configuration or the function itself) and the icon pack to somewhere outside VSCode’s directory, to avoid asking admin permission every time after updating

**Comment by jens1o** [comment]
That's right. It updates the icon Pack.

**Comment by be5invis** [comment]
However it asks me EVERY TIME when I start Code.

**Comment by jens1o** [comment]
Yes. It's scheduled each time you start code. You need to do that, to hide the warning.

**Comment by be5invis** [comment]
BUT WHY? You COULD move the file identification part and the icon pack part to some place does not need admin.

**Comment by jens1o** [comment]
Please look into the faq. We inject some code in Code, because it is not supported by Code, yet. And in order to overwrite the files(in a dir which is protected) we need admin.

**Comment by jens1o** [comment]
see https://github.com/robertohuertasm/vscode-icons#disclaimer

**Comment by be5invis** [comment]
@jens1o 
I think you can separate the file/folder identification part (configuration or the function itself), and the icon pack to somewhere else, outside VSCode’s directory, like ~/.vscode.

**Comment by jens1o** [comment]
But in order to load this icon pack in the main file of code, we need to change some code. We can't change the process.

Soon, in the next release, we'll use the official vscode integration. It is scheduled for the 13th.

**Comment by be5invis** [comment]
@jens1o I mean, your injected code can provide some kind of interface, and load configurations, and icon pack from somewhere outside VSC’s directory.

**Comment by jens1o** [comment]
Each time after update, these files will be replaced. So, after all, you need to do that each update.

**Comment by be5invis** [comment]
@jens1o @robertohuertasm
I mean that, here, you inject JS and CSS into Code, right?
Every time you update, these two files only changes a small part, file/folder-icon association in particular.
So, if you can use some way, to separate these part into a separate file outside VSCode's directory, then every time your plugin updates, it does not need to update the injected part every time.

**Comment by jens1o** [comment]
I mean the update of VSC.

**Comment by be5invis** [comment]
But you update the plugin too fast.

**Comment by jens1o** [comment]
**Please**, look into the faq.

**Comment by jens1o** [comment]
see https://github.com/robertohuertasm/vscode-icons#faqs

**Comment by be5invis** [comment]
**I've already read it.**

You update the plugin fast because you want to support new icons. Yes, I can understand.
However, **the way that supporting new icons can be improved** so that, you do not have to change the injected part which requires admin permission. So then, you can update it at any frequency you like while not asking admin.

**Comment by jens1o** [comment]
> support new icons
and keep supporting the vscode Insider Version.

For each icon, we need to add css classes and js methods. So here we are. For each update, we *need* to update the 2 files.

**Comment by be5invis** [comment]
@jens1o 
You can try to inject the browser window’s CSS on-the-fly...
I mean, move the code used to build CSS into the JS part.
Just an advice.

**Comment by jens1o** [comment]
Even we could optimize this(btw we also have to update the js, not only css). We have 10 days left for the new integration. I think we should be focused on the new integration.

**Comment by robertohuertasm** [comment]
Hi @be5invis, @jens1o. I think you both have your reasons. What @be5invis proposes is not way too crazy. However, I agree with @jens1o that maybe it's not worth wasting our time on that while we're being pushed by Microsoft to avoid injecting code into VSCode asap.

In order to reduce the warning from showing so often we could save all the json files (file and folder icons) in the user's folder, then load them and generate the css on runtime -as the new API does right now (in insiders version)-. However, we should also control what kind of deployment are we going to do, if it's only icons, core functionality or both in order to run the autoinstall functionality or not. And we should also control whether the extension is already installed, it has been disabled and so on... And even doing all that we couldn't help but needing admin privileges from time to time because we need some times to change the code due to a bug or a change in the vscode code.

I think, as my colleague @jens1o that we should focus on taking the extension to the official path. My idea is to keep both functionalities for the moment (the official and the legacy way) until the official way supports more or less the same experience as the current version does.

As per my conversations with the VSCode team they're willing to provide tabs and editor icons in the next release (October maybe). User associations are out of the scope at the moment. They should need more user demands in order to see the benefit of such an implementation. I think it's really a must and will allow users to fine tune what the extension's creators provide but they don't see it this way, for the moment. Anyway, I'm thinking of maybe extending VSCode with a PR or something once we arrive to that point. Or maybe use Github reactions in order to see what people thinks about it and put some preassure on the VSCode team.

@be5invis I've reduced the issue's title and put the old title in the description. It's not nice to have such an enormous title :wink:  Nevertheless, thank you very much for your ideas, they're very welcome! :+1: 

I'd suggest to keep an eye on this - as I'm aware that lots of users have been complaining about it - and wait until the first integration point is accomplished in order to see if this is worth our time or not. 

PS:
By the way, @be5invis if your VSCode is asking for admin privileges every time you start it something wrong is going on as this should not be happening. I'll reinstall again the extension and see if it's solved. If not, raise another issue and we'll dig into it.

**Comment by robertohuertasm** [comment]
I'm closing this. See #328
