### ISSUE TITLE
vscode-icons breaks VSCode 1.4.0 for some users

### ISSUE THREAD

**Issue by bpasero** [robertohuertasm/vscode-icons#276]
We are receiving numerous bug reports from users over the past days where either VS Code does not show anything or parts of the UI are broken. I am raising the issue here and ask if you are aware of these issues:

* https://github.com/Microsoft/vscode/issues/11576
* https://github.com/Microsoft/vscode/issues/11578
* https://github.com/Microsoft/vscode/issues/11265
* https://github.com/Microsoft/vscode/issues/10566

**Comment by robertohuertasm** [comment]
@bpasero I'm aware of these issues but it would be nice if these users could be redirected to this repo and report here so we could try to know how exactly they messed up with the files. They explain that they cannot see something but they don't say what they did before. Did they update the extension? Did they execute some of the vscode-icons commands? In what order? I mean, we need this issues to be reported here so we can get proper feedback.

Anyway, we'll try to reproduce this and see if this can be diminished or eradicated. Hopefully, with the next API integration these issues will not raise so often.

By the way, in the repository's readme we have a FAQ and a Disclaimer section explaining that there's always a possibility to make VSCode crash and that the solution is to reinstall it 99% of the times. They could use the generated .bak files but it's usually faster and safer the "reinstalling option".

**Comment by bpasero** [comment]
Imho vscode-icons should detect that the replacement of JS files failed and restore the bak automatically (e.g. by doing a checksum of the resulting JS file and seeing if the operation suceeded or not).

**Comment by robertohuertasm** [comment]
I've added a guard in the injection process in order to avoid double injection which is somehow how all things were getting messed. It will be released in a minute. 

Btw, I've seen that you have released the new 1.5.0 stable version. I was somehow under the impression that this was going to happen on Sept 12th (as per @aeschli email conversations) and has caught me by surprise. :disappointed:  I'm still working on it as this is a busy week for me and not have much time.

Related [#11288](https://github.com/Microsoft/vscode/issues/11288)
