### ISSUE TITLE
not working using newest version(1.5.1) of vscode (Linux)

### ISSUE THREAD

**Issue by leido** [robertohuertasm/vscode-icons#278]
- I'm using Visual Studio Code Version [1.5.1] [Stable]
- I'm using the extension version [1.9.1]
- My system is: [linux mint 18] [x86_64]
- [yes ] I'm sure this issue is not a *duplicate*?

**Description:**

[doesn't work in newest vscode]

just don't show up all the icons, I guess this extension may conflict with new version of vscode, because new version(1.5.1) adds new feature: file icon theme.

**Comment by gep13** [comment]
@leido I just came here to see if anyone else was having issues with this extension after installing the 1.5 version of VSCode.  The extension still seems to work fine for me, however, if I try to enable a "File Icon Theme", I see the following:

![image](https://cloud.githubusercontent.com/assets/1271146/18379673/a67b6554-766b-11e6-82e2-bf67248cfdba.png)

i.e. I now have duplicate icons for each file.

@robertohuertasm what is the plan going forward with this extension?  To convert it to a File Icon Theme, or something else?

Thanks for your hard work to date on this extension, and I am happy to read that the VSCode team have been working with you as they added this new extension point into VSCode.

**Comment by leido** [comment]
@gep13 my situation is the following when I **disable** File Icon Theme in Preference, vscode-icons just doesn't show up.
Maybe we use different OS arch or it is because I upgrade my vscode editor from version 1.4
![screenshot-2016-09-09-161932](https://cloud.githubusercontent.com/assets/6065941/18380328/5ce83938-76a9-11e6-909d-22218ec3f899.png)
![screenshot-2016-09-09-161906](https://cloud.githubusercontent.com/assets/6065941/18380329/5ce9f994-76a9-11e6-88b2-a492d6d695ae.png)

Frankly speaking, I think this icon theme is much pretter than seti icon :)

**Comment by gep13** [comment]
@leido I am on a Windows machine, and just this morning, I updated from 1.4 to 1.5 of VSCode.  After doing that, there was an update for vscode-icons, which I installed, then restarted VSCode with admin permissions, and everything worked as normal.

**Comment by avih** [comment]
@gep13  I had the same problem too, my solution was to:
1. Uninstall the extension.
2. Re-install vscode (I use the zip download extracted to a custom folder, so I just deleted the folder and re-extracted vscode 1.5.1 to that folder again). It _should_ keep all your settings and other extensions intact, but just in case first make a backup of `~/.vscode`.
3. Possibly install the extension again if you're not happy with the new built in icons.

**Comment by robertohuertasm** [comment]
@avih, there's no need for such a complex workaround. Let me explain how it should work:
If you want to uninstall the extension safely, first you have to execute `icons disable` command. This will restore the original files. No need for backups or something like this. Plus, reinstalling VSCode will not erase your settings or your installed extensions so don't be afraid to do it if you please.

@gep13 has followed the perfect path in order to keep using vscode-icons so if you're in the situation that the icons have disappeared just follow his instructions.

@leido it seems that there's something affecting the permissions of the vscode folders when installing the latest version in Linux. See [here](https://github.com/robertohuertasm/vscode-icons/issues/140#issuecomment-245841274). Let me know if that works the issue.

Finally, @gep13, as stated in the readme, the idea is to keep both custom and official support for a while, until official support gets closed to what the extension offers now (tab icons, editors open icons, custom file associations...).

**Comment by gep13** [comment]
>@robertohuertasm said...
Finally, @gep13, as stated in the readme, the idea is to keep both custom and official support for a while, until official support gets closed to what the extension offers now (tab icons, editors open icons, custom file associations...).

Makes perfect sense.  Thanks for getting back to me about this.

**Comment by robertohuertasm** [comment]
@avih I didn't mean to be rude but I think that, by the tone of your comment, you got upset or something. Anyway, if you don't bother to read the manual then don't complaint later. You have to be aware of why things are working the way that they are and, obviously, this is something that you will only get by reading the manual. 

I'm happy that you found your own solution but I was only trying to make it simpler for people who may come here seeking for help, that's it.

**Comment by avih** [comment]
Yes, I did get upset that your solution to safely uninstall includes anything other than pressing the uninstall button.

That being said, I do understand it's probably a side effect of the transition from 1.4 to 1.5 and the previous version of the extension's injection.

I do appreciate the solution you provide to people who might bump into this issue, but I still think that the best solution would be that an update to the latest version or installing and uninstalling the latest version should take care of the cruft possibly left there by earlier version.

**Comment by robertohuertasm** [comment]
@avih it's not a thing I can control as it doesn't seem to exist any uninstall hook on the extension API, thus the only possibility is a user action to completely remove all the injected code. It's in the disclaimer. And please, don't get upset and be more cooperative next time. A good attitude is always positive for everyone.

**Comment by avih** [comment]
> @avih it's not a thing I can control as it doesn't seem to exist any uninstall hook on the extension API

Which is why I added "or updating/installing and uninstalling the latest version should take care of the cruft possibly left there by earlier version" - which in my experience it did not. Surely at some stage of update/restart/use/uninstall a newer version of the extension can do something about it. At the very least inform the user that such an issue may exist and somehow point to a solution.

Regardless, code has bugs and issues, that's how it is and no one would get upset over a bug, I certainly did not (well.. at least not about bugs which don't wipe your filesystem ;) ). IMO a better wording would have been "Yes, we know there could be such issue due to $whatever, please do A, B, C to restore order".

Anyway, thanks for maintaining this extension.

**Comment by leido** [comment]
@robertohuertasm I exec `sudo chown -R $(whoami) /usr/share/code` command, but still the icons don't show up

**Comment by leido** [comment]
@robertohuertasm I checked another same issue and found the solution:
1. Icon Update
2. restart
3. icon enable

**Comment by robertohuertasm** [comment]
Many thanks @leido for your feedback! I'm going to close this issue.
