### ISSUE TITLE
CSS/PostCSS fallback not working

### ISSUE THREAD

**Issue by jbw91** [robertohuertasm/vscode-icons#559]
## Checklist

- [x] I'm sure this issue is not a *duplicate*?

## Screenshot

![screen shot 2016-12-19 at 11 29 53 am](https://cloud.githubusercontent.com/assets/5883616/21324316/7eca8810-c5de-11e6-8699-f770acbae94d.png)

## Description

As you can see from the image above, the CSS icons are no longer working. From #556 I gather it's due to my workspace settings where I specify the following file association:

```json
"files.associations": {
    "*.css": "postcss"
},
```

Obviously I assume there's no icon for postcss, however before the latest update to `4.2.0`, it would properly fall back to the CSS icon. Now it simply shows the non-associated file icon.

## Expected functionality

If I associate my files with something else that doesn't have an icon, it should fall back to the default for that file extension.

**Comment by JonathanWolfe** [comment]
There is an icon for PostCSS ([icon here](https://github.com/robertohuertasm/vscode-icons/blob/master/icons/file_type_postcss%402x.png)).

**Comment by JimiC** [comment]
@JonathanWolfe That icon is associated with `.pcss` extension.

**Comment by robertohuertasm** [comment]
Hi both of you. Icons can only be linked to languages via language services. VSCode provides a few out of the box but you can add others via extension (that was your case @JonathanWolfe).

With the latest release we tried to leverage the power of languages in order to allow users further customization. Before that, we only used direct icon extension association so the user never had the opportunity to choose anything else. We decided that `.css` extension had this icon and end of the discussion.

@jbw91, fallback functionality cannot be accomplished with the current vscode api but we're working in a series of enhancements that will allow user customization. Stay tuned.

For the moment, our only option is make the changes to support postcss language id. Are you using [this extension](https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS)?

**Comment by jbw91** [comment]
@robertohuertasm Yes, I am using the PostCSS extension.

**Comment by robertohuertasm** [comment]
Ok @jbw91, we'll provide a language association for you as soon as possible.

**Comment by JimiC** [comment]
@robertohuertasm 

Working on this I stumbled upon the following behavior:
Using ```{ icon: 'postcss', extensions: [], languages: [languages.postcss] }```, if `.pcss` and `.postcss` are present  or `.css` files have been associated with `PostCSS`, and the user has not installed the `PostCSS` syntax extension, the files have the default icon.
Upon installing the extension the `postcss` icon is displayed on all of them.

Is this the expected behavior?

**Comment by robertohuertasm** [comment]
Yes it is. If `.css` was still using a `file extension matching` then it will work as expected. But as now it's also using `language matching` this is how the current API is working.

**Comment by megalofauna** [comment]
![postcss-icon-bug](https://user-images.githubusercontent.com/8394554/37261093-c2498246-2567-11e8-92f9-96cb28499da7.jpg)

I installed [the postcss language syntax extension](https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS) and am wondering why the PostCSS icon isn't showing up in the Exlorer pane.

New to VS Code. Not sure if my issue is related to this older issue, but didn't want to post a dup. 

As you can see from my screenshot, I've attempted to fix the issue by associating `.pcss` files with 'postcss'. No luck. 

Suggestions?

**Comment by jens1o** [comment]
@megalofauna You're not using vscode, perhaps you [want to install it](https://github.com/vscode-icons/vscode-icons#installation)?

**Comment by JimiC** [comment]
@jens1o It has already been addressed in another issue the user opened.

**Comment by jens1o** [comment]
@JimiC Pardon me, didn't saw the relationship :/

**Comment by megalofauna** [comment]
Sorry for the confusion on my end, folks. As @JimiC noted, my issue is resolved. 👍
