### ISSUE TITLE
Linux issue : .../.config/code-oss-dev vs .../.config/code/...

### ISSUE THREAD

**Issue by 40tude** [robertohuertasm/vscode-icons#600]
Bonjour
I compiled and run VSCode on a Raspberry (Debian) and it works
I'm able to use Python (0.55) and C/C++ (0.9.3) extensions
 
However I'm not able to install the vscode-icons extension
Indeed after the Reload here is the message I get : Activating extension `robertohuertasm.vscode-icons` failed: ENOENT: no such file or directory, open '/home/philippe/.config/Code/User/vsicons.settings.json'.

Looking around in my home directory I can see /home/philippe/.config/code-oss-dev/User directory but no /home/philippe/.config/Code/User directory

Are you aware of such behavior?
Is it an issue on my side?

Any advise or idea is more than welcome.
Best regards, Philippe

**Comment by robertohuertasm** [comment]
It seems that the function we use to resolve the `user folder` is not working for you. We'll take a look at it and let you know.

Thanks for reporting this! 😁

**Comment by robertohuertasm** [comment]
Hey Philippe,

you said you compiled `vscode` yourself and that's why you're having this issue. Basically, you should change the `name` property of the `package.json` to `Code`. 

We determine the folder where `vscode` stores user data by looking at the appName by doing a simple mapping. As we don't have access to the `name` property we stick to the association:
- appname == Visual Studio Code -> user folder == Code
- appname == Visual Studio Code Insiders -> user folder == Code - Insiders

Let me know if that does the trick.

**Comment by 40tude** [comment]
I just modify the name as you requested and recompile 
Works like a charm
Many thanks for the fast answer and the trick
I hope my feedback helped, Philippe

PS : I'm not sure to understand why there are differents name nor what OSS stand for.

**Comment by JimiC** [comment]
Confirming @robertohuertasm. This only happens if you self-compile `vscode`.

**Comment by JimiC** [comment]
OSS = Open Source Software
