### ISSUE TITLE
Updating VSCode disables the vscode-icons

### ISSUE THREAD

**Issue by sridharmane** [robertohuertasm/vscode-icons#86]
I am using vscode-insiders (v1.4.0-insider) and every day when vscode updates the vscode-icons get disabled. Not sure if this is expected behaviour.

**Comment by robertohuertasm** [comment]
@sridharmane this is the expected behaviour. On every update, original files are modified and a direct action from the user is needed to inject the code again. I could certainly automate this process but I thought that given that code injection is needed it should be an active action from the user although, being an Insider's user myself I'm reconsidering other options... 😉
